export enum Genre {
  ALL = "*",
  Action = "Action",
  Adventure = "Adventure",
  Animation = "Animation",
  Comedy = "Comedy",
  Crime = "Crime",
  Documentary = "Documentary",
  Drama = "Drama",
  Family = "Family",
  Fantasy = "Fantasy",
  History = "History",
  Horror = "Horror",
  Music = "Music",
  Mystery = "Mystery",
  Romance = "Romance",
  "Science Fiction" = "Science Fiction",
  Thriller = "Thriller",
  "TV Movie" = "TV Movie",
  War = "War",
  Western = "Western",
}
