export enum RepositoryKind {
  USERS_REPOSITORY = "USERS_REPOSITORY",
  MOVIES_REPOSITORY = "MOVIES_REPOSITORY",
  REVIEWS_REPOSITORY = "REVIEWS_REPOSITORY",
  COMMENTS_REPOSITORY = "COMMENTS_REPOSITORY",
}
